spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/software_catalogue_management
spring.datasource.username=springuser
spring.datasource.password=devpass102938

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true