spring.application.name=backend
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/software_catalogue_management}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:springuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:devpass102938}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health

app.auth.session-ttl-hours=24
